### ISSUE TITLE
can not work with 3.4.6

### ISSUE THREAD

**Issue by lnh089** [HugoHasenbein/redmine_preview_office#14]
Hello,
I have installed this plugin,but cannot preview office documents,below are logs:

Started GET "/attachments/preview_office/23" for 192.168.16.33 at 2019-09-25 15:06:17 +0800
Processing by AttachmentsController#preview_office as HTML
  Parameters: {"id"=>"23"}
  Current user: admin (id=1)
Creating preview with libreoffice failed (pid 11061 exit 1):
Command: cd /tmp/d20190925-11002-x5y9ma; 'soffice' --convert-to pdf '/opt/redmine/files/2019/09/190925114957_2f239f4c27f617e9dfc2683b995a519f.docx'; mv '190925114957_2f239f4c27f617e9dfc2683b995a519f.pdf' '/opt/redmine/tmp/thumbnails/23_651c2e7327911aad6069e3a6f2a43a211a082a046c86bf25bded6c5619eda7bc.pdf'
Completed 404 Not Found in 1142ms (ActiveRecord: 1.5ms)
[root@localhost redmine]#
![redmine](https://user-images.githubusercontent.com/21374477/65577756-0b157980-dfa7-11e9-8034-224cfd9c6fe7.png)

**Comment by mhenman** [comment]
I had the exact same error, in my case it turned out to be that the user that Redmine runs as (in my case www-data) could not create the .config directory in its home directory.  I ran the following and now it's working great:

$ sudo mkdir /var/www/.config
$ sudo chown www-data /var/www/.config

Note: I'm running 3.4.6 on ubuntu 16.04, apache 2.4.18 and passenger 5.0.27.

**Comment by lnh089** [comment]
> I had the exact same error, in my case it turned out to be that the user that Redmine runs as (in my case www-data) could not create the .config directory in its home directory. I ran the following and now it's working great:
> 
> $ sudo mkdir /var/www/.config
> $ sudo chown www-data /var/www/.config
> 
> Note: I'm running 3.4.6 on ubuntu 16.04, apache 2.4.18 and passenger 5.0.27.

Hi mhenman,
thank you!
I have config redmine as below,and set the .config with you idea,but still not work.
![rm11](https://user-images.githubusercontent.com/21374477/66621458-e06a2880-ec16-11e9-9262-bc872f632b80.png)
